name: 0.96 i2c Display"
description: 0.96 LCD Display"
url: "https://github.com/ccritix/0.96-OLED/tree/main/0_96_display/lcd_display"
version: "1.1.2"
slug: "0_96_display"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
gpio: true
full_access: true
devices: 
  - "/dev/i2c-1"
privileged: 
  - "SYS_ADMIN"
hassio_api: true